steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/qwiklabs-gcp-00-4976f22e9ecb/node-app:$COMMIT_SHA'
      - '.'

  # Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/qwiklabs-gcp-00-4976f22e9ecb/node-app:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-cloudrun-service'
      - '--image=gcr.io/qwiklabs-gcp-00-4976f22e9ecb/node-app:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=us-central1'  # Update with your desired region
      - '--allow-unauthenticated'  # Remove if authentication is required

options:
  logging: CLOUD_LOGGING_ONLY  # or NONE if you don't need logs
  #logsBucket: 'devops-bucket-11'  # Replace with your Cloud Storage bucket name
