steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/node-app:$COMMIT_SHA'
      - '.'

  # Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/node-app:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-cloudrun-service'
      - '--image=gcr.io/$PROJECT_ID/node-app:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=$REGION'  # Update with your desired region
      - '--allow-unauthenticated'  # Remove if authentication is required

images:
  - 'gcr.io/$PROJECT_ID/my-docker-image:$COMMIT_SHA'
